### ISSUE TITLE
爬虫请教

### ISSUE THREAD

**Issue by baifengbai** [ztmzzz/UESTC_course_data#1]
老哥你好，想咨询下高考数据的爬虫能否加您个微信bai7426

**Comment by baifengbai** [comment]
您好，我想把专科的数据也搞一下从哪个入口进？

**Comment by ztmzzz** [comment]
> 您好，我想把专科的数据也搞一下从哪个入口进？

可以从[这里](https://gkcx.eol.cn/school/search?argschtype=%E4%B8%93%E7%A7%91%EF%BC%88%E9%AB%98%E8%81%8C%EF%BC%89)获得专科的学校

**Comment by baifengbai** [comment]
还有一些其他问题想付费咨询下，方便留个邮箱沟通下吗？

**Comment by ztmzzz** [comment]
> 还有一些其他问题想付费咨询下，方便留个邮箱沟通下吗？

可以先把大概的问题列一下
ztmzzz@ztmzzz.top

**Comment by baifengbai** [comment]
发邮件了，辛苦有空看一下

**Comment by ztmzzz** [comment]
> 发邮件了，辛苦有空看一下

已回复，可以看看你的垃圾邮箱有没有我的邮件
